POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Node.js"
}

###

GET http://localhost:3333/courses?orderBy=title

### 

GET http://localhost:3333/courses/245c1444-2bc1-49a9-9e33-ad3467e99661